name: axia-env
channels:
  - conda-forge
  - defaults
dependencies:
  # --- PythonとJupyterの基本環境 ---
  - python=3.11
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets

  # --- PlotlyとJupyterLab拡張機能 ---
  # CondaにJupyterLabと互換性のあるバージョンを解決させる
  - plotly
  - jupyterlab-plotly-extension

  # --- 主要な分析・バックテスト用ライブラリ ---
  - ta-lib
  - pandas
  - pyarrow
  - boto3
  - python-dateutil
  - tqdm
  - scikit-learn
  - pytest
  - nbformat # 互換性のために明示的に追加

  # --- pipでのみインストール可能なパッケージ ---
  - pip
  - pip:
    - vectorbt
    - Backtesting
